version: '3'

services:
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Seoul"

  doomz:
    container_name: library-management
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      TZ: "Asia/Seoul"
      DB_ADDR: ${DB_ADDR}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    env_file:
      - .env